
volumes:
  postgres-data:

services:
  postgres:
    image: postgres:alpine
    volumes:
      # We'll store the postgres data in the 'postgres_data' volume we defined:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - published: ${LTREE_PG_PORT:-5432}
        target: 5432
    environment:
      POSTGRES_USER: ${USER:-you}
      POSTGRES_HOST_AUTH_METHOD: trust